[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = "Lab 5"
[tool.poetry.dependencies]
Flask-JWT = "^0.3.2"
Flask-SQLAlchemy = "^2.4"
flask = "==1.0.2"
python = "^3.8"
